version: '3.8'
services:
  web:
    container_name: sistema_web_container
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=SistemaDB;User Id=sa;Password=Password_12345;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    container_name: sistema_db_container
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password_12345
    ports:
      - "1433:1433"